### ISSUE TITLE
fix: crashes on iOS

### ISSUE THREAD

**Issue by jtkeyva** [alnitak/shader_buffers#2]
**Description**

run on iOS using XCode crashes on some screens and gives this:

[ERROR:flutter/shell/platform/darwin/graphics/FlutterDarwinContextMetalImpeller.mm(42)] Using the Impeller rendering backend.
flutter: The Dart VM service is listening on http://127.0.0.1:49175/6l_-nd5F8Qo=/
flutter: LayerBuffer.init() loaded: true  assets/shaders/shader2_bufferA.frag
flutter: LayerBuffer.init() loaded: true  assets/shaders/shader2_main.frag
flutter: LayerBuffer.init() loaded: true  assets/shaders/test_isself_buffer_a.frag
flutter: LayerBuffer.init() loaded: true  assets/shaders/test_isself_main.frag
flutter: LayerBuffer.init() loaded: true  assets/shaders/shader1_bufferA.frag
flutter: LayerBuffer.init() loaded: true  assets/shaders/shader1_main.frag
flutter: LayerBuffer.init() loaded: true  assets/shaders/shader2_bufferA.frag
flutter: LayerBuffer.init() loaded: true  assets/shaders/shader2_main.frag
flutter: LayerBuffer.init() loaded: true  assets/shaders/mouse2.frag
flutter: LayerBuffer.init() loaded: true  assets/shaders/shader2_bufferA.frag
flutter: LayerBuffer.init() loaded: true  assets/shaders/shader2_main.frag
flutter: LayerBuffer.init() loaded: true  assets/shaders/mouse2.frag
flutter: LayerBuffer.init() loaded: true  assets/shaders/shader2_bufferA.frag
flutter: LayerBuffer.init() loaded: true  assets/shaders/shader2_main.frag
flutter: LayerBuffer.init() loaded: true  assets/shaders/mouse2.frag
flutter: LayerBuffer.init() loaded: true  assets/shaders/shader1_bufferA.frag
flutter: LayerBuffer.init() loaded: true  assets/shaders/shader1_main.frag
flutter: LayerBuffer.init() loaded: true  assets/shaders/test_isself_buffer_a.frag
flutter: LayerBuffer.init() loaded: true  assets/shaders/test_isself_main.frag
flutter: LayerBuffer.init() loaded: true  assets/shaders/shader1_bufferA.frag
flutter: LayerBuffer.init() loaded: true  assets/shaders/shader1_main.frag
flutter: LayerBuffer.init() loaded: true  assets/shaders/test_isself_buffer_a.frag
flutter: LayerBuffer.init() loaded: true  assets/shaders/test_isself_main.frag
flutter: LayerBuffer.init() loaded: true  assets/shaders/page_curl.frag
flutter: LayerBuffer.init() loaded: true  assets/shaders/page_curl.frag
flutter: LayerBuffer.init() loaded: true  assets/shaders/water.frag
-[MTLDebugRenderCommandEncoder validateCommonDrawErrors:]:5775: failed assertion `Draw Errors Validation
Fragment Function(water_fragment_main): missing buffer binding at index 4 for speed[0].
'

**Steps To Reproduce**

run on iOS

**Expected Behavior**

Work like it does on web

**Screenshots**

**Additional Context**

**Comment by alnitak** [comment]
Hi @jtkeyva 

I think impeller is not yet ready for shaders. Can you please try running the example with impeller disabled?
`flutter run --no-enable-impeller`

**Comment by jtkeyva** [comment]
@alnitak you are correct, it's working. really awesome stuff!

widgets look slightly pixely/grainy. wonder if impeller will fix that?

**Comment by alnitak** [comment]
I think it will be fixed for sure, but don't really know how much it will take
