### ISSUE TITLE
feat: Apply to videos

### ISSUE THREAD

**Issue by nanox77** [alnitak/shader_buffers#5]
Hi, very good library, it is very useful, thank you!.

Is it possible to use this for videos? How could I use it? 

Thanks!!

**Comment by alnitak** [comment]
Hi,

you should send every video frame to a buffer, so having a video package that exposes each frame to the dev is mandatory. But this implies an incredible performance issue I think! :)

A solution could be to give the video widget to the buffer as the child, but I never tried.

The best solution could be to integrate shaders into the native code of the video package, but this means managing native code (C/C++).

**Comment by nanox77** [comment]
Great, thank you very much for your response, I'll look into that!
