### ISSUE TITLE
fix: Shader screen upside down and noise input shaders not displaying correctly

### ISSUE THREAD

**Issue by Laurie-Lin** [alnitak/shader_buffers#6]
**Description**

Hello, first of all, thank you for providing the shader_buffers library, which makes it easier for me to port shaders from https://www.shadertoy.com/ to Flutter.

However, I encountered some issues while using it.

## 1. Shader screen upside down

This can be reproduced in many shader codes. The behavior is that the screen rendered by ShaderBuffer in Flutter is upside down.

## 2. Some shaders requiring noise input do not display correctly

**Steps To Reproduce**

All the example code can be found at

https://github.com/mengyanshou/shader_buffers/tree/main/example_issue

**Expected Behavior**

Normal as shadertoy

**Screenshots**
<img width="912" alt="截屏2024-09-10 18 47 34" src="https://github.com/user-attachments/assets/628fa858-bd4b-427f-926f-6178894d8a1e">

**Additional Context**

Using a simple HTML https://github.com/mengyanshou/shader_buffers/blob/main/example_issue/index.html

<img width="1367" alt="截屏2024-09-10 18 35 16" src="https://github.com/user-attachments/assets/bcd95810-2d47-4901-a96d-00d3dd271893">

can render this shader correctly.

This might not be related to ShaderBuffer, but I would like to ask how to make such shaders work correctly.

**Comment by alnitak** [comment]
Hi @mengyanshou 

> This can be reproduced in many shader codes. The behavior is that the screen rendered by ShaderBuffer in Flutter is upside down.

that's correct! The OpenGL ES has the origin coords in the bottom left corner, while using Flutter shaders the coords are on the upper left corner (the same origin used by images for example).

To fix this you can do something like:
```
fragCoord.y = 1.0 - fragCoord.y;
```
as the first line of `mainImage()` function.

I noticed that the new `flutter_gpu` doesn't have this issue because it uses OpenGLES directly.

**Comment by Laurie-Lin** [comment]
I'll try. Thank you very much

**Comment by Laurie-Lin** [comment]
It doesn't actually work, but I can rotate the screen while the canvas is drawing, is it possible for shader_buffers to update flutter_gpu support, do you have any suggestions for the second question

**Comment by alnitak** [comment]
Rotating the widget is not what you might want. You should vertically flip it instead and play with that `X = 1.0 -X;` with some other parameter.

Regarding the `flutter_gpu`, I think I will port this, but for now, it is using Impeller graphics engine which is experimental and working only on iOS, Mac and somehow on Android.
I did some experiments [here](https://github.com/alnitak/flutter_gpu_test).

**Comment by Laurie-Lin** [comment]
Okay. Thank you so much.

**Comment by Laurie-Lin** [comment]
I use this code to make my shaders work correctly

```glsl
void main() {
    // Shader compiler optimizations will remove unused uniforms.
    // Since [LayerBuffer.computeLayer] needs to always set these uniforms, when 
    // this happens, an error occurs when calling setFloat()
    // `IndexError (RangeError (index): Index out of range: index should be less than 3: 3)`
    // With the following line, the compiler will not remove unused
    float tmp = (iFrame/iFrame) * (iMouse.x/iMouse.x) * 
        (iTime/iTime) * (iResolution.x/iResolution.x);
    if (tmp != 1.) tmp = 1.;

    // Get the original fragCoord
    vec2 fragCoord = FlutterFragCoord().xy;

    // Flip the y coordinate
    fragCoord.y = iResolution.y - fragCoord.y;

    // Pass the flipped fragCoord to mainImage
    mainImage(fragColor, fragCoord * tmp);
}
```

This way I don't have to modify each shader. Additionally, I am trying to create a library called awesome_flutter_shaders to port shaders I found on shadertoy to flutter.

Thanks for your shader_buffers

**Comment by alnitak** [comment]
The biggest limitation when we want to try importing shaders, is that the buffer layer of ShaderToy is basically a texture with floats values. In Flutter you can get/set only RGAB8888 images to give back as textures. So you could somehow easily copy/paste shaders with just the `image` layer from ShaderToy.
 Things may change with Impeller.
